services:
  # Add this new MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db  # Persistent storage for MongoDB
    networks:
      - host-net
    restart: unless-stopped

  collector:
    entrypoint: ["sh", "-c", "sleep 1 && python modbus_collector.py"]
    depends_on:
      simulator:
        condition: service_started
      mongodb:  # Add dependency
        condition: service_started
    build:
      context: .
      dockerfile: collector/Dockerfile
    volumes:
      - ./config:/config
    environment:
      - CONFIG_DIR=/config
      # Add explicit MongoDB URI override:
      - MONGO_URI=mongodb://mongodb:27017  # Direct container connection
    restart: unless-stopped
    networks:
      - modbus-net
      - host-net
    # REMOVED: extra_hosts (no longer needed)

  simulator:  # No changes needed
    build:
      context: .
      dockerfile: simulator/Dockerfile
    volumes:
      - ./config:/config
    ports:
      - "1502-1599:1502-1599"
    networks:
      - modbus-net
    init: true
    stop_grace_period: 1s
    stop_signal: SIGTERM

  flask:
    depends_on:
      mongodb:  # Add dependency
        condition: service_started
    build:
      context: .
      dockerfile: flask/Dockerfile
    volumes:
      - ./config:/config
      - ./flask/static:/app/static
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - MONGO_URI=mongodb://mongodb:27017  # Direct container connection
    networks:
      - host-net
    restart: unless-stopped
    # REMOVED: extra_hosts (no longer needed)

  cert-generator:  # No changes needed
    image: alpine:latest
    volumes:
      - ./nginx/generate-certs.sh:/generate-certs.sh
      - ./nginx/ssl:/certs
    command: ["sh", "/generate-certs.sh"]
    networks:
      - host-net

  nginx:  # No changes needed
    image: macbre/nginx-http3:latest
    container_name: nginx
    depends_on:
      cert-generator:
        condition: service_completed_successfully
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./flask/static:/app/static
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    networks:
      - host-net

# Add volume declaration for MongoDB
volumes:
  mongodb_data:  # Named volume for MongoDB persistence

networks:
  modbus-net:
    driver: bridge
  host-net:
    driver: bridge
    name: host-access
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
